#!/bin/sh

# Get date (two formats)
if [ -n "$2" ]; then
    LONGDATE=`date -d "$2" "+%B %d, %Y"`
    SHORTDATE=`date -d "$2" "+%m-%d-%Y"`
else
    LONGDATE=`date "+%B %d, %Y"`
    SHORTDATE=`date "+%m-%d-%Y"`
fi

# Current version number
CURRENTVERSION=1.4.2

# Last date
LASTDATE=06-29-2011

if [ "x$1" = "x" ]
then
	echo "Usage: $0 <version number | \"newdate\"> [revision date]"
	echo ""
	echo "Run this script with the name of the new version (i.e \"2.0b1\") to"
	echo "update version number and modification date in files."
	echo "Use the \"newdate\" argument if you want to keep the current version"
	echo "number and just update the modification date."
	echo ""
	echo "Current version=$CURRENTVERSION"
	echo "Current Modification date=$LASTDATE"
	echo ""
	exit 1
fi

# Keep track of last version, as it is needed to update quickstart guide pages
lastversion=$CURRENTVERSION

# What's the new version number (if any)?
newversion=$1
if [ "x$newversion" = "xnewdate" ]
then
    # No new version number, just a new version date
    newversion=$CURRENTVERSION
fi

# Update version number icinga.spec
perl -i -p -e "s/Version: .*/Version: $newversion/;" icinga.spec

# Update version number Doxyfile
#perl -i -p -e "s/PROJECT_NUMBER         = .*/PROJECT_NUMBER         = $newversion/;" Doxyfile

# Update version number in Makefile.in
perl -i -p -e "s/ICINGA_VERSION=.*/ICINGA_VERSION=$newversion/;" Makefile.in
# needs to be done in current Makefile too (not dependant on configure!)
perl -i -p -e "s/ICINGA_VERSION=.*/ICINGA_VERSION=$newversion/;" Makefile

# Update version number and release date in main HTML page
perl -i -p -e "s/>Version .*</>Version $newversion</;" html/main.html
perl -i -p -e "s/releasedate\">.*<\//releasedate\">$LONGDATE<\//;" html/main.html
perl -i -p -e "s/new in Icinga [0-9].*<\/a>/new in Icinga $newversion<\/a>/;" html/main.html

# Update version number and release date in common code
perl -i -p -e "s/VERSION \".*\"/VERSION \"$newversion\"/;" include/common.h
perl -i -p -e "s/MODIFICATION_DATE \".*\"/MODIFICATION_DATE \"$SHORTDATE\"/;" include/common.h

# Update version number and release date in main code
perl -i -p -e "s/Version: .*/Version: $newversion/;" base/icinga.c
perl -i -p -e "s/Version: [0-9].*/Version: $newversion/;" base/icingastats.c

# Update version number and release date in configure script and configure.in
perl -i -p -e "s/PKG_VERSION=.*/PKG_VERSION=\"$newversion\"/;" configure
perl -i -p -e "s/PKG_REL_DATE=.*\"/PKG_REL_DATE=\"$SHORTDATE\"/;" configure
perl -i -p -e "s/PKG_VERSION=.*/PKG_VERSION=\"$newversion\"/;" configure.in
perl -i -p -e "s/PKG_REL_DATE=.*\"/PKG_REL_DATE=\"$SHORTDATE\"/;" configure.in

# Update RPM spec file with version number
perl -i -p -e "s/%define version .*/%define version $newversion/;" icinga.spec

# Update this file with version number and last date
perl -i -p -e "s/^CURRENTVERSION=.*/CURRENTVERSION=$newversion/;" update-version
perl -i -p -e "s/^LASTDATE=.*/LASTDATE=$SHORTDATE/;" update-version

# Update version number and release date in IDOUtils
perl -i -p -e "s/IDOMOD_VERSION \".*\"/IDOMOD_VERSION \"$newversion\"/;" module/idoutils/include/idomod.h
perl -i -p -e "s/IDOMOD_DATE \".*\"/IDOMOD_DATE \"$SHORTDATE\"/;" module/idoutils/include/idomod.h
#perl -i -p -e "s/thisversion=\".*\"/thisversion=\"$newversion\"/;" module/idoutils/db/scripts/upgradedb.in
#perl -i -p -e "s/lastversion=\".*\"/lastversion=\"$newversion\"/;" module/idoutils/db/scripts/upgradedb.in
#perl -i -p -e "s/legacyversion=\".*\"/legacyversion=\"$newversion\"/;" module/idoutils/db/scripts/upgradedb.in
#perl -i -p -e "s/thisversion=\".*\"/thisversion=\"$newversion\"/;" module/idoutils/db/scripts/installdb.in
perl -i -p -e "s/IDO2DB_VERSION \".*\"/IDO2DB_VERSION \"$newversion\"/;" module/idoutils/include/ido2db.h
perl -i -p -e "s/IDO2DB_DATE \".*\"/IDO2DB_DATE \"$SHORTDATE\"/;" module/idoutils/include/ido2db.h
perl -i -p -e "s/SOCKDEBUG_VERSION \".*\"/SOCKDEBUG_VERSION \"$newversion\"/;" module/idoutils/src/sockdebug.c
perl -i -p -e "s/SOCKDEBUG_DATE \".*\"/SOCKDEBUG_DATE \"$SHORTDATE\"/;" module/idoutils/src/sockdebug.c
perl -i -p -e "s/FILE2SOCK_VERSION \".*\"/FILE2SOCK_VERSION \"$newversion\"/;" module/idoutils/src/file2sock.c
perl -i -p -e "s/FILE2SOCK_DATE \".*\"/FILE2SOCK_DATE \"$SHORTDATE\"/;" module/idoutils/src/file2sock.c
perl -i -p -e "s/LOG2IDO_VERSION \".*\"/LOG2IDO_VERSION \"$newversion\"/;" module/idoutils/src/log2ido.c
perl -i -p -e "s/LOG2IDO_DATE \".*\"/LOG2IDO_DATE \"$SHORTDATE\"/;" module/idoutils/src/log2ido.c

# Update dbversion in IDOUtils
# mysql INSERT INTO icinga_dbversion (name, version) VALUES ('idoutils', '1.3.0') ON DUPLICATE KEY UPDATE version='1.3.0';
# pgsql SELECT updatedbversion('1.3.0');
# oracle DEFINE ICINGA_VERSION=1.3.0

#perl -i -p -e "s/VALUES \(\'idoutils\', \'.*\'\)/VALUES \(\'idoutils\', \'$newversion\'\)/;" module/idoutils/db/mysql/mysql.sql
#perl -i -p -e "s/version=\'.*\'/version=\'$newversion\'/;" module/idoutils/db/mysql/mysql.sql
#perl -i -p -e "s/updatedbversion\(\'.*\'\)/updatedbversion\(\'$newversion\'\)/;" module/idoutils/db/pgsql/pgsql.sql
#perl -i -p -e "s/ICINGA_VERSION=.*/ICINGA_VERSION=$newversion/;" module/idoutils/db/oracle/oracle.sql


