#!/bin/sh

expected_platform="sparc"
platform=`uname -p`

if [ ${platform} != ${expected_platform} ]; then
    echo "\n\n\n\tThis package must be installed on a ${expected_platform} architecture\n"
    echo "\tAborting installation.\n\n\n"
    exit 1
fi

exit 0
