#! /bin/sh

if [ "z$1" = "z" ] ; then
	echo You must specify an architecture to build for!
	exit 1
fi

case "$1" in
	solaris)
		LD_RUN_PATH=/usr/lib:/usr/local/lib
		autoreconf
		PATH=.:..:$PATH configure --with-cgiurl=/icinga/cgi-bin \
--with-htmurl=/icinga \
--with-lockfile=/var/run/icinga.pid \
--with-icinga-user=icinga \
--with-icinga-grp=icinga \
--with-command-user=icinga \
--with-command-grp=www \
--prefix=/usr/local \
--exec-prefix=/usr/local/sbin \
--bindir=/usr/local/sbin \
--sbindir=/usr/local/lib/icinga/cgi \
--libexecdir=/usr/local/lib/icinga/plugins \
--datadir=/usr/local/share/icinga \
--sysconfdir=/etc/icinga \
--localstatedir=/var/log/icinga \
--with-mail=/usr/bin/mailx
		make pkgclean
		make all
		make pkgset
		;;
	*)
		echo Platform $1 is not currently supported
		exit 1
		;;
esac

exit 0
