#!/bin/sh

SVCCFG=/usr/sbin/svccfg
GREP=/usr/bin/grep
USERADD=/usr/sbin/useradd
GROUPADD=/usr/sbin/groupadd

${SVCCFG} import /var/svc/manifest/application/icinga.xml

chown -R icinga:icinga /etc/icinga /var/icinga

exit 0
