###############################
# Makefile for Include Files
#
# Last Modified: 05-12-2010
###############################

clean:
	rm -f *~

distclean: clean
	rm -f config.h locations.h snprintf.h

devclean: distclean
